# Generated by Django 5.1.3 on 2024-12-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='file_measurement',
            field=models.FileField(null=True, upload_to='measurements/'),
        ),
    ]
