# Generated by Django 5.1.3 on 2024-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_measurement_file_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='file_measurement',
            field=models.FileField(default='default_file.txt', upload_to='measurements/'),
        ),
    ]
