# Generated by Django 5.1.3 on 2024-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('under_review', 'Рассмотрение'), ('rejected', 'Отказ'), ('accepted', 'Принят')], default='created', max_length=20),
        ),
    ]
