# Generated by Django 5.1.3 on 2024-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurement_file_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='file_measurement',
            field=models.FileField(upload_to='measurements/'),
        ),
    ]
