# Generated by Django 5.1.3 on 2024-12-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_measurement_file_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='file_measurement',
            field=models.FileField(blank=True, null=True, upload_to='measurements/'),
        ),
    ]
